server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Arquitectura-de-Software-02-2023/server-config.git
          ignoreLocalSshSettings: true
          hostKey: github.com,
          hostKeyAlgorithm: ssh-rsa
          privateKey: |
                      -----BEGIN RSA PRIVATE KEY-----
                      

  application:
    name: server-config
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
encrypt:
  key: t5ijtY]d:Sfq#6F%2C/R,t#3PB)NdU



